#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 196

#define USB_SUSPEND_WAKEUP_DELAY 0
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "6pvmR/jZZgJe"
#define LAYER_STATE_8BIT

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

